### ISSUE TITLE
Info i APK (nie znajdę nic w internecie)

### ISSUE THREAD

**Issue by codinger-cutie** [Kashumy/kashumy.github.io#2]
1. Pobierz jakiś APK exporter, zapisz nim Tiled Maply z telefonu i wyślij mi wyeksportowany APK przez hosting plików np. files.fm (zobacz gdzie exporter trzyma pliki, wejdź do tego folderu przy wrzucaniu pliku).
2. Podaj info swojego żelowego cienkopisu (bardzo cienki czarny) (info z zakrętki).

**Comment by Kashumy** [comment]
co dalej

**Comment by codinger-cutie** [comment]
Jak wrzuciłeś APK to podaj link w odpowiedzi do mojego komentarza.

**Comment by codinger-cutie** [comment]
W przypadku APK exportera przy eksporcie będzie komunikat o zapisie ze ściężką, przy wrzucaniu pliku wejdź do tej ścieżki. Lub w ustawieniach exportera będzie gdzieś 'Save location' czy coś.

**Comment by Kashumy** [comment]
mam lepszy pomyśł zdekompiluje apk
zmienię je na plik pobierany i zrobię z niego zipa nastepnie zrobie dla niego repo
a ty to pobierzesz :)

**Comment by Kashumy** [comment]
wrazie czego masz apk tool m więc jeżeli nie będzie na twoje sdk to sobie zmienisz

**Comment by Kashumy** [comment]
masz tu linka do pobrania apk
https://github.com/Kashumy/TitledMaPLY-APKS/
poinformuj mnie kiedy go pobierzesz
oraz czy działa
wrazie czego mogę poprostu zrobić kod html kturym będziesz mugł to robić .
W końcu znam się na wirtualizacji : 3

**Comment by codinger-cutie** [comment]
Dzięki, pobrałem, mogę Ci dać linki do Minecrafta (legalny 1.20 nie crack) (rozmiar plików to 0,8GB, nie będą na GitHubie) (pliki to .apks użyj [Split APKs Installer](https://play.google.com/store/apps/details?id=com.aefyr.sai) ). Korzystaj z Markdowna od GitHuba, tutaj też jest. 

Jak zobaczyć czy masz Minecrafta z Google Play
Wejdź w Apktoolu M w Details przy Minecrafcie (moje .apks, wziąłem oryginalny MC tylko) zobacz Signature matches, jeśli będzie **matches** to znaczy, że masz oryginalnego Minecrafta z Google Play na telefonie, czyli plik z mojego archiwum ma taki sam podpis co Minecraft na telefonie

**Comment by codinger-cutie** [comment]
Jeszcze instrukcja 2 (nie wiem zrób nawet zdjęcia tego długopisu).
